name: 📄 Documentation issue
description: Found an issue in the documentation? You can use this one!
title: '[DOCS] <description>'
labels: ['📄 aspect: text']
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the question or issue, also include what you tried and what didn't work
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add screenshots if applicable
    validations:
      required: false
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else we should know about this issue?
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        You can also message me [here](https://twitter.com/prathamesh_117) for any other feedback!
        Feel free to reach out to me on my other handles [here](https://prathamesh-shanbhag.vercel.app), for a faster response!
