name: Other
description: Use this for any other issues.
title: '[OTHER]'
labels: ['🚦 status: awaiting triage']
body:
  - type: markdown
    attributes:
      value: '# Other issue'
  - type: textarea
    id: issuedescription
    attributes:
      label: What would you like to share?
      description: Provide a clear and concise explanation of your issue.
    validations:
      required: true
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else we should know about this issue?
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        You can also message me [here](https://twitter.com/prathamesh_117)
        Feel free to check out my other handles [here](https://prathamesh-shanbhag.vercel.app)
