on:
  fork:
  push:
    branches: [main]
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened]
  pull_request_review_comment:
    types: [created]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "<h1>It's great having you contribute to this project</h1> Thank you so much, I appreciate all of you! :sparkles:"
          pr-message: "<h1>It's great having you contribute to this project</h1> Thank you so much, I appreciate all of you! :sparkles:"
          footer: 'You can also message me on Twitter (https://twitter.com/prathamesh_117) for any other feedback! Feel free to reach out to me on my other handles as well! (https://www.prathamesh-shanbhag.com/)'
